# Generated by Django 5.1.2 on 2024-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('not-completed', 'Not Completed'), ('finished', 'Finished')], default='ongoing', max_length=20),
        ),
    ]
