# Generated by Django 5.1.2 on 2024-11-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_habit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('not-completed', 'Not Completed'), ('finished', 'Finished')], default='not-completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracker.habit'),
        ),
        migrations.AlterField(
            model_name='habitstreak',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='tracker.habit'),
        ),
    ]
